AllCops:
  Exclude:
    - 'bundle_bin/*'
    - 'vendor/bundle/**/*'

# Offense count: 3
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100

# Offense count: 2
Style/Documentation:
  Enabled: false

# Offense count: 2
Style/RegexpLiteral:
  MaxSlashes: 0

Style/FileName:
  Exclude:
    - bin/*
    - bundle_bin/*
    - exe/*
